apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alibaba-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules: 
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/status    
    - services
    - services/status
    verbs:
    - patch
