apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alibaba-cloud-controller-manager:alibaba-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
roleRef:
  kind: Role
  name: alibaba-cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: openshift-cloud-controller-manager
    name: cloud-controller-manager
